export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_COURSE = 'GET_COURSE';
export const GET_ALL_COURSES = 'GET_ALL_COURSES';
export const GET_PURCHASED_COURSES = 'GET_PURCHASED_COURSES';
export const GET_AUTHORED_COURSES = 'GET_AUTHORED_COURSES';
export const COURSE_LOADING = 'COURSE_LOADING';
export const COURSE_NOT_FOUND = 'COURSE_NOT_FOUND';
export const CLEAR_CURRENT_USER = 'CLEAR_CURRENT_USER';




