export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CLEAR_CURRENT_USER = 'CLEAR_CURRENT_USER';
export const PURCHASE_COURSE = 'PURCHASE_COURSE';


// Course Types
export const CREATE_COURSE = 'CREATE_COURSE';
export const UPDATE_COURSE = 'UPDATE_COURSE';
export const GET_COURSE = 'GET_COURSE';
export const GET_ALL_COURSES = 'GET_ALL_COURSES';
export const GET_PURCHASED_COURSES = 'GET_PURCHASED_COURSES';
export const GET_AUTHORED_COURSES = 'GET_AUTHORED_COURSES';
export const EDIT_COURSE = 'EDIT_COURSE';
export const DELETE_COURSE = 'DELETE_COURSE';
export const COURSE_LOADING = 'COURSE_LOADING';
export const SET_CURRENT_COURSE = 'SET_CURRENT_COURSE';
export const COURSE_NOT_FOUND = 'COURSE_NOT_FOUND';
export const GET_PURCHASE_TOKEN = 'GET_PURCHASE_TOKEN';
export const SELECTED_COURSE_FIELD_CHANGE = 'SELECTED_COURSE_FIELD_CHANGE';
export const SET_COURSE_LOADED = 'SET_COURSE_LOADED';

// export const UPDATE_AUTHORED_COURSE = 'UPDATE_AUTHORED_COURSE';
// export const UPDATE_PURCHASED_COURSE = 'UPDATE_PURCHASED_COURSE';



// Lessons in Courses
export const DELETE_NEW_COURSE_LESSON = 'DELETE_NEW_COURSE_LESSON';
export const DELETE_SELECTED_COURSE_LESSON = 'DELETE_SELECTED_COURSE_LESSON';
export const ADD_NEW_COURSE_LESSON = 'ADD_NEW_COURSE_LESSON';
export const ADD_SELECTED_COURSE_LESSON = 'ADD_SELECTED_COURSE_LESSON';

export const ADD_COURSE_LESSON = 'ADD_COURSE_LESSON';
export const UPDATE_NEW_COURSE = 'UPDATE_NEW_COURSE';
export const UPDATE_NEW_LESSON = 'UPDATE_NEW_LESSON';
export const LESSON_LOADING = 'LESSON_LOADING';



// Lesson Types
export const SAVE_LESSON = 'SAVE_LESSON';
export const GET_LESSON = 'GET_LESSON';
export const GET_ALL_LESSONS = 'GET_LESSONS';
export const EDIT_LESSON = 'EDIT_LESSON';
export const DELETE_LESSON = 'DELETE_LESSON';
export const SET_CURRENT_LESSON = 'SET_CURRENT_LESSON';

// UI Reducer
export const EXPAND_LESSON_LIST = 'EXPAND_LESSON_LIST';
export const COLLAPSE_LESSON_LIST = 'COLLAPSE_LESSON_LIST';
export const TOGGLE_LESSON_LIST = 'TOGGLE_LESSON_LIST';





