export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CLEAR_CURRENT_USER = 'CLEAR_CURRENT_USER';

// Course Types
export const GET_COURSE = 'GET_COURSE';
export const GET_ALL_COURSES = 'GET_ALL_COURSES';
export const GET_PURCHASED_COURSES = 'GET_PURCHASED_COURSES';
export const GET_AUTHORED_COURSES = 'GET_AUTHORED_COURSES';
export const EDIT_COURSE = 'EDIT_COURSE';
export const DELETE_COURSE = 'DELETE_COURSE';
export const COURSE_LOADING = 'COURSE_LOADING';
export const COURSE_NOT_FOUND = 'COURSE_NOT_FOUND';

// Lesson Types
export const GET_LESSON = 'GET_LESSON';
export const GET_ALL_LESSONS = 'GET_LESSONS';
export const EDIT_LESSON = 'EDIT_LESSON';
export const DELETE_LESSON = 'DELETE_LESSON';
export const LESSON_LOADING = 'LESSON_LOADING';





